package ua.com.todd.gpx.parser

const val TAG_GPX = "gpx"
const val TAG_TRACK = "trk"
const val TAG_SEGMENT = "trkseg"
const val TAG_TRACK_POINT = "trkpt"
const val TAG_LAT = "lat"
const val TAG_LON = "lon"
const val TAG_ELEVATION = "ele"
const val TAG_TIME = "time"
const val TAG_WAY_POINT = "wpt"
const val TAG_ROUTE = "rte"
const val TAG_ROUTE_POINT = "rtept"
const val TAG_NAME = "name"
const val TAG_DESC = "desc"
const val TAG_CMT = "cmt"
const val TAG_SRC = "src"
const val TAG_LINK = "link"
const val TAG_NUMBER = "number"
const val TAG_TYPE = "type"
const val TAG_TEXT = "text"